services:
  - type: web
    name: vibefilms
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED  
        value: 1